### ISSUE TITLE
look_at doesn't work if camera has parent with transform

### ISSUE THREAD

**Issue by wijnen** [Aeva/m.grl#200]
Plan:
`var base = new please.GraphNode();`
`var camera = new please.Camera();`
`var graph = new please.SceneGraph()`
`graph.add(base);`
`base.add(camera);`
`camera.look_at = base;`
`camera.up_vector = [0, 0, 1];`
`camera.location = [10, 0, 0];`
`base.rotation = [0, 30, 0]`

Expected:
See the objects at the origin (where base is) at an angle.

Observed:
Camera seems to be in correct position, but it is looking the wrong way.  This seems to be because __view_matrix_driver in m.camera.js creates the matrix from this.look_at, which I'm guessing is either the world or local position of the object.  In this example, neither of them would be correct; the world location corrected for the camera transform would be required.

**Comment by Aeva** [comment]
The current way M.GRL handles cameras is wrong because it assumes that local space and world space are the same for the camera object.

The work-around I have for this right now is to leave the camera parented to the graph root, and have a proxy object for the camera.  Then do
```
camera.location = proxy;
```

I currently use [https://github.com/Aeva/m.grl/blob/d10ee07164c01b28f788ee50f8e165bd24461845/demos/train_terrain/project.js#L177](this hack) so that I can allow the camera to rotate slowly around another graph node.

**Comment by Aeva** [comment]
This should work correctly now
