### ISSUE TITLE
Animation playback is wrong for some test files

### ISSUE THREAD

**Issue by Aeva** [Aeva/m.grl#213]
I'm not sure if this is a problem in the blender exporter or the jta importer yet.

The file in question is "anitest3.blend".  There are three bones in the animation that are not parented to each other.  The playback is very different in Blender than it is in M.GRL. 

Unsure if this is related to either #91 or #88.

**Comment by wijnen** [comment]
I think I have found the problem, but I don't know what the cause is yet.  The location attribute of the object is wrong.  Looking at the club, in Blender it is reported as (-1.6, 0, 0.46), but D.objects['club'].matrix_local.decompose()[0] is (0, 0, 0).  When using matrix_basis instead of matrix_local, it does return the reported location.  I don't know yet what matrix_basis is, and if it does the right thing for other objects and properties as well.

**Comment by wijnen** [comment]
http://blender.stackexchange.com/questions/15240/relationship-between-global-vertex-coordinates-and-mesh-objects-matrix-attribut explains the difference, and matrix_basis is certainly not what should be used.

However, it does show what the problem is: the action properties are in matrix_basis-space, so they need to be transformed with matrix_parent_inverse to become matrix_local-space, which should be stored in the jta file.

**Comment by wijnen** [comment]
I think I may have found half of the problem.  The exporter assumes that bones are stored in world coordinates (which you said they are), but it doesn't limit this assumption to bones.  So the mesh location is also compensated, which makes it wrong.

This part of the fix is to add an if statement to the compensation, so the part in common.py:export becomes:
```
if self.obj.type != "MESH":
    local_matrix = pose.matrix.inverted() * self.obj.matrix_world
```

It makes the club move correctly; I don't know if it breaks other things.  It also doesn't make the other sticks move yet, so I'm going to look into that now.  (It's also a better idea to check if it's a bone, not if it's not a mesh, but this works now, it can be made pretty later.)

**Comment by Aeva** [comment]
oh!  good catch

**Comment by wijnen** [comment]
No, actually it isn't.  That code is used when the parent is an armature, and that normally only happens to meshes, because bones are not objects (so it could happen when you parent a bone to a different armature, but why would anyone do that?)  I just disabled that statement effectively, and it seemed to work, but it didn't, it was just wrong in a different way.

The problem seems to be that no matrix contains the distance from the head to the tail of the bone, every armature matrix is about the head, but the child mesh is relative to the tail.  I can get the tail, but it seems like there should be a way to use a matrix instead of vectors.  But I need to find a matrix which contains the translation from the head to the tail of the bone, and I haven't found it so far.

**Comment by wijnen** [comment]
Now I did find the problem.  It was in the line I referenced above.  As I wrote, the outcome to be stored in local_matrix must be the conversion from the parent bone to the mesh object.  Because matrix_local of the mesh is relative to the tail, and nothing else includes the tail, it cannot be used.  This is probably why you used matrix_world to begin with.

However, you use pose.matrix.inverted(), which is the inverse conversion from the armature to the bone in its posing position.  This only works if the armature is located at the origin and not rotated or scaled.  If it is, the armature's world matrix must be included in the computation.

The target is to get the conversion from the bone to the mesh, and since the mesh needs to use its world matrix, the bone must do the same.  That means that the line should be:
```js
local_matrix = (self.obj.parent.matrix_world * pose.matrix).inverted() * self.obj.matrix_world
```
I tested it on this file, and it works, but it should be tested on other files to be sure it doesn't break anything.
