### ISSUE TITLE
Animations are only imported if instance is called without arguments on a file with more than one model

### ISSUE THREAD

**Issue by wijnen** [Aeva/m.grl#85]
__jta_add_action is called on line 4013, from inside two if statements: one for the function being called without arguments, and one for it containing more than one model.  Neither of those tests is useful; actions should always be imported.

I think moving it to the code block for a named object should fix the problem, but I didn't look into a possible problem of finding out which model the action belongs to.  A workaround is of course to add an unused extra model to a single model file and not calling it with an argument.

**Comment by wijnen** [comment]
Ok, this isn't as bad as I originally thought.  Am I right that only rigid body animations are supported, not vertex deformations?  In that case an animation with less than one object isn't very useful anyway.

It is still a bug, and it should be fixed, but it's low priority.

**Comment by Aeva** [comment]
The outer conditional is for the situation where you export a singular object from Blender and instance it without any arguments.  It should be updated to be all objects, not just models; it was written before empties and other such things could be exported as a mild optimization (ignores the extra graph node that m.grl would generate).
```
if (models.length + empties.length === 1) {
    return scene.instance(models[0]);
}
```

The second test, for if "scene.actions" is defined, is so that if there are actions present, load them up, otherwise we're done.  In regards to mapping models to actions, I think I may have misunderstood what actions meant in blender's terminology - I need to do a little more research on this before I can properly comment, but you are correct that m.grl only supports rigid body animations at the moment.  Odds are that I may have understood something wrong and may need to re-think part of how jta animations are loaded up.  Basically what I want actions to do in m.grl is to be the handle for playing different animations for a given scene (so like, multiple characters moving about in a cut scene or something would be an action, but also things pertaining to just a single character like a walk cycle or such).

Last bit, a thing to keep in mind is that scene.instance is a recursive function.  If it is called without any arguments, then it creates the full tree; if it is called with a named object, it should return the tree starting at that object.

**Comment by Aeva** [comment]
Marking this as open ended, as I'm a bit confused.

**Comment by wijnen** [comment]
I was also confused, so my report wasn't as clear as it should have been.  I think I figured some things out by now, so here's my understanding.  I hope it helps clear up your confusion as well:

Actions in Blender work on armatures.  They then deform or transform other objects such as meshes which are linked to them.  For some reason I wrote the above with the incorrect assumption that one armature is always linked to exactly one mesh, and that therefore an action can be seen as owned by one mesh.  This is incorrect.  Any number of objects (including multiple meshes) can have the armature as a parent.  Therefore, the action is a property of the scene, not of the mesh.  You have this implemented properly.

The bug here is therefore not that the action is not activated when requesting a single object: that is correct, because actions don't work for an object without the context of its scene.

The bug is that when there is only one object in the scene (the if statement you quoted), the optimization of not wrapping it in an extra object is good, but it should still activate actions on the scene.  After all, the entire scene did load.

That's what I make of it now.  I may change my mind again later. :-P

The file I was using where I found the problem was a Suzanne which flapped its ears, but I didn't save it.  Obviously, the ear-flapping didn't work anyway, because it was a mesh deformation.  A working example would be a simple single-mesh model that has an action of hopping from one spot to the next, like this: http://wijnen.dtdns.net/~shevek/m.grl/doc/hop.blend

**Comment by Aeva** [comment]
Ah!  You are correct, that is a problem :)  To reiterate for my own benefit:
- [ ] "export singular object without parent empty edge case optimization" currently prevents actions from being exported.

Note that with armature, bones are exported as a variation on empties, so this edge case wouldn't get hit for rigs, but it would get hit for objects that have keyframes without a rig.

**Comment by Aeva** [comment]
Alright, I uploaded a fix.  Closing this for now.
